### ISSUE TITLE
【Progate:VII】画像の表示について

### ISSUE THREAD

**Issue by sice11** [sice11/post_app#1]
「ProgateVIIの5.ユーザー画像を表示しよう」について質問があります。

【質問内容】
htmlファイルに画像を表示させるための記述を行おうとしているのですが、
index.html.erbとshow,html.erbと記述が少し異なります。
これはなぜでしょうか？

index.html.erb

```
<img src = "<%= "/user_images/#{user.image_name}" %>"
```

show.html.erb

```
<img src = "<%= "/user_images/#{@user.image_name}" %>">
```

userの前に@のあるなしが見られました。

【前提】
public
____└ user_images
________ └ 2.jpg(ユーザ画像がこの階層に保存)

・DB

```
rails g migration ~
```

より、画像ファイルを保存するカラムを作成完了

migrationファイルの編集も完了

**Comment by sice11** [comment]
【考察】

usrs_controller.rbを確認すると

```
  def index
    @users = User.all
  end
  
  def show
    @user = User.find_by(id: params[:id])
  end
```

indexには@userの定義がされていないことがわかりました。

**Comment by good1luck21** [comment]
この辺り苦手ですね！

index.html.erb
```ruby
@users.each do | user |
  <img src = "<%= "/user_images/#{user.image_name}" %>"
end
```

show.html.erb
```ruby
<img src = "<%= "/user_images/#{@user.image_name}" %>">
```

indexでは繰り返し文で表示していて、showはそのままコントローラーの変数を使っているので、インスタンス変数をそのまま使っています！

**Comment by sice11** [comment]
そうでした。
ありがとうございます。
