### ISSUE TITLE
インスタンスメソッドの定義

### ISSUE THREAD

**Issue by sice11** [sice11/post_app#2]
https://prog-8.com/rails5/study/9/5#/13

![無題](https://user-images.githubusercontent.com/61615289/89262422-871e2a80-d66a-11ea-9789-b6b71efbd6d0.png)

```
def user
    return User.find_by(id: self.user_id)
end
```

ここでのselfに関する解説がよくわかりませんでした。
「インスタンスメソッド内で、selfはそのインスタンス自身を指す。」
ここでselfがさしているのは、「User」でいいでしょうか？
それとも「user」でしょうか？

**Comment by good1luck21** [comment]
この場合はメソッドのuserですね！

**Comment by sice11** [comment]
ありがとうございます。
def user の部分。
